services:
  - type: web
    name: creo-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host=0.0.0.0 --port=10000
    plan: free
    envVars:
      - key: MONGO_URL
        value:mongodb+srv://jiyajoshi:<R9CQ36q2V.gwsi.>@cluster0.4gsehd9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: DB_NAME
        value: Project 0

  - type: static
    name: creo-frontend
    rootDir: frontend
    buildCommand: yarn install && yarn build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://creo-backend.onrender.com